server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/accountdb
    username: account
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
