server:
  port: 8087

spring:
  application:
    name: card-service
  datasource:
    url: jdbc:postgresql://localhost:5432/carddb
    username: card
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
