server:
  port: 8086

spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:postgresql://localhost:5432/loandb
    username: loan
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
